export const ABOUT = '/about'
export const CONTACT = '/contact'
export const HOME = '/home'
export const LOGIN = '/login'
export const LOGOUT = '/logout'
export const LOST_PASSWORD = '/lost-password'
export const PROFILE = '/profile'
export const REGISTER = '/register'